# Dataset simpel
lets start by simple iterating through the dataset from : https://archive.ics.uci.edu/ml/datasets/EEG+Eye+State#
We will use this to base further work on



In [1]:
%load_ext autoreload
%autoreload 2
from sys import path
import tensorflow as tf
from scipy.io import arff

path.append('..')

2022-06-09 20:42:31.880175: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-09 20:42:31.880209: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


First make a simple dataset

In [2]:
from src.data.make_dataset import get_eeg
datapath = get_eeg(data_dir="../data/raw")
path = "../data/raw"
from src.data.make_dataset import get_eeg_data
data = get_eeg_data(datapath)

1712128/1696428 [==============================] - 1s 1us/step


2022-06-09 20:42:53.611 | INFO     | src.data.make_dataset:get_eeg:27 - Data is downloaded to /tmp/.keras/datasets/eeg.
2022-06-09 20:42:53.612 | INFO     | src.data.make_dataset:get_eeg_data:34 - /tmp/.keras/datasets/eeg already exists, skipping download


let's check the dataset

In [3]:
# simple data set with data
from src.data.make_eeg_data import EEGListDataset
dsNew = EEGListDataset(data=data[0].tolist())
x,y = dsNew[12000]


let's implement a simple iterator

In [4]:
class BaseIterator:
  def __init__(self, data, n: int):
    self.n = n
    # we generate some dummy data
    self.data = data

  def __iter__(self):
    # startindex; this makes the first index 0
    self.idx = -1
    # we return the full object when iter() is called
    return self

  def __next__(self):
    # for every iteration, __next__ is called
    # as long as the idx is not bigger than the data
    # we need to do -1, because we will increase idx directly after this
    if self.idx < len(self.data) - 1:
      self.idx += 1
      return self.data[self.idx]
    else:
      raise StopIteration

myclass = BaseIterator(dsNew, n=5)
myiter = iter(myclass) # this calles the __iter__ method and sets idx to -1



And presto, we can 

In [10]:
for x in range(0,4): # this calls the __next__ method
  x,y = myiter.__next__()
  print(x)
  print(y)

tensor([4360.5100, 4055.3800, 4291.2800, 4140.5100, 4340.5100, 4621.5400,
        4082.0500, 4615.9000, 4204.6200, 4231.7900, 4222.0500, 4295.3800,
        4613.3300, 4429.2300], dtype=torch.float64)
tensor(1)
tensor([4378.9700, 4076.9200, 4301.0300, 4155.3800, 4344.1000, 4615.3800,
        4078.9700, 4612.8200, 4201.5400, 4232.8200, 4229.2300, 4302.5600,
        4623.5900, 4448.7200], dtype=torch.float64)
tensor(1)
tensor([4401.5400, 4097.4400, 4312.8200, 4168.2100, 4346.1500, 4603.5900,
        4075.3800, 4606.1500, 4192.3100, 4234.3600, 4235.3800, 4315.9000,
        4631.7900, 4465.6400], dtype=torch.float64)
tensor(1)
tensor([4409.7400, 4106.6700, 4315.9000, 4170.7700, 4344.1000, 4597.9500,
        4067.6900, 4596.9200, 4176.9200, 4222.5600, 4228.2100, 4321.5400,
        4618.9700, 4464.6200], dtype=torch.float64)
tensor(1)
