# Dataset simpel
lets start by simple iterating through the dataset from : https://archive.ics.uci.edu/ml/datasets/EEG+Eye+State#
We will use this to base further work on



In [11]:
%load_ext autoreload
%autoreload 2
from sys import path
import tensorflow as tf
from scipy.io import arff

path.append('..')

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


First make a simple dataset

In [12]:
from src.data.make_dataset import get_eeg
datapath = get_eeg(data_dir="../data/raw")
path = "../data/raw"
from src.data.make_dataset import get_eeg_data
data = get_eeg_data(datapath)

2022-06-13 20:25:57.990 | INFO     | src.data.make_dataset:get_eeg:27 - Data is downloaded to /tmp/.keras/datasets/eeg.
2022-06-13 20:25:57.991 | INFO     | src.data.make_dataset:get_eeg_data:34 - /tmp/.keras/datasets/eeg already exists, skipping download


let's check the dataset

In [13]:
# simple data set with data
from src.data.make_eeg_data import EEGListDataset
dsNew = EEGListDataset(data=data[0].tolist())
x,y = dsNew[12000]


let's implement a simple iterator

In [14]:
class BaseIterator:
  def __init__(self, data, n: int):
    self.n = n
    # we generate some dummy data
    self.data = data

  def __iter__(self):
    # startindex; this makes the first index 0
    self.idx = -1
    # we return the full object when iter() is called
    return self

  def __next__(self):
    # for every iteration, __next__ is called
    # as long as the idx is not bigger than the data
    # we need to do -1, because we will increase idx directly after this
    if self.idx < len(self.data) - 1:
      self.idx += 1
      return self.data[self.idx]
    else:
      raise StopIteration

myclass = BaseIterator(dsNew, n=5)
myiter = iter(myclass) # this calles the __iter__ method and sets idx to -1



And presto, we can iterate data!

In [15]:
for x in range(0,4): # this calls the __next__ method
  x,y = myiter.__next__()
  print(x)
  print(y)

tensor([4329.2300, 4009.2300, 4289.2300, 4148.2100, 4350.2600, 4586.1500,
        4096.9200, 4641.0300, 4222.0500, 4238.4600, 4211.2800, 4280.5100,
        4635.9000, 4393.8500], dtype=torch.float64)
tensor(0)
tensor([4324.6200, 4004.6200, 4293.8500, 4148.7200, 4342.0500, 4586.6700,
        4097.4400, 4638.9700, 4210.7700, 4226.6700, 4207.6900, 4279.4900,
        4632.8200, 4384.1000], dtype=torch.float64)
tensor(0)
tensor([4327.6900, 4006.6700, 4295.3800, 4156.4100, 4336.9200, 4583.5900,
        4096.9200, 4630.2600, 4207.6900, 4222.0500, 4206.6700, 4282.0500,
        4628.7200, 4389.2300], dtype=torch.float64)
tensor(0)
tensor([4328.7200, 4011.7900, 4296.4100, 4155.9000, 4343.5900, 4582.5600,
        4097.4400, 4630.7700, 4217.4400, 4235.3800, 4210.7700, 4287.6900,
        4632.3100, 4396.4100], dtype=torch.float64)
tensor(0)
